name: Chat Weather

on:
  schedule:
    - cron: "0 6,18 * * *" #시간 마다 실행
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install

      - name: Generate readme
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build-svg.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: taeJunHub
          author_email: kisdo0084@naver.com
          message: "Auto updating my Chat Weather"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}